import type { Colourway, OffTheRailProduct, SizeStock } from "@/types/off-the-rail";
import assets from "./offTheRailAssets.json";

type AssetKey = keyof typeof assets;

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

/** Photos are generated by scripts/off-the-rail (Higgsfield + rembg); a = first colourway, b = second. */
function colourway(num: AssetKey, variant: "a" | "b", id: string, name: string, hex: string): Colourway {
  const set = assets[num];
  const front = set[`${variant}-front`];
  const side = set[`${variant}-side`];
  return {
    id,
    name,
    hex,
    front: { ...front, src: BASE_PATH + front.src },
    side: { ...side, src: BASE_PATH + side.src },
  };
}

function sizes(xs: number, s: number, m: number, l: number, xl: number): SizeStock[] {
  return [
    { size: "XS", stock: xs },
    { size: "S", stock: s },
    { size: "M", stock: m },
    { size: "L", stock: l },
    { size: "XL", stock: xl },
  ];
}

export const OFF_THE_RAIL_PRODUCTS: OffTheRailProduct[] = [
  {
    id: "reach-shirt",
    number: 1,
    name: "Reach Shirt",
    price: 68,
    status: "in_stock",
    description: "Boxy camp-collar shirt in cotton poplin, a dry-brush hand reaching up from the hem.",
    colourways: [
      colourway("01", "a", "white", "White", "#F3F2EE"),
      colourway("01", "b", "black", "Black, bone hand", "#1D1D1F"),
    ],
    sizes: sizes(0, 6, 2, 9, 4),
  },
  {
    id: "scrawl-tee",
    number: 2,
    name: "Scrawl Tee",
    price: 42,
    status: "selling_fast",
    description: "Heavyweight boxy tee, sprayed by hand so the scrawl wraps off the side seam.",
    colourways: [
      colourway("02", "a", "black-orange", "Black, orange", "#1A1A1A"),
      colourway("02", "b", "chalk-cobalt", "Chalk, cobalt", "#EEECE6"),
    ],
    sizes: sizes(1, 2, 0, 3, 1),
  },
  {
    id: "blend-in-tee",
    number: 3,
    name: "Blend In Tee",
    price: 38,
    status: "in_stock",
    description: "Oversized off-white tee with marker lettering written straight onto the screen.",
    colourways: [
      colourway("03", "a", "cream", "Cream", "#EFE9DA"),
      colourway("03", "b", "black-red", "Black, red", "#1B1B1D"),
    ],
    sizes: sizes(5, 8, 7, 2, 6),
  },
  {
    id: "two-faces-tee",
    number: 4,
    name: "Two Faces Tee",
    price: 42,
    status: "in_stock",
    description: "Garment-dyed tee, one continuous line drawing two faces about to speak.",
    colourways: [
      colourway("04", "a", "washed-charcoal", "Washed charcoal", "#4B4B4E"),
      colourway("04", "b", "sand", "Sand, charcoal line", "#D6C8AE"),
    ],
    sizes: sizes(3, 5, 6, 4, 0),
  },
  {
    id: "unbothered-tee",
    number: 5,
    name: "Unbothered Tee",
    price: 40,
    status: "selling_fast",
    description: "Burgundy heavyweight tee, one word set top to bottom with a small foil star.",
    colourways: [
      colourway("05", "a", "burgundy", "Burgundy", "#6A1F2B"),
      colourway("05", "b", "forest", "Forest green", "#1F4A36"),
    ],
    sizes: sizes(0, 2, 1, 4, 2),
  },
  {
    id: "ink-drip-shirt",
    number: 6,
    name: "Ink Drip Shirt",
    price: 72,
    status: "in_stock",
    description: "Camp-collar shirt with ink strokes swept over both shoulders and left to run.",
    colourways: [
      colourway("06", "a", "olive", "Olive", "#5E6833"),
      colourway("06", "b", "ecru-navy", "Ecru, navy strokes", "#ECE5D2"),
    ],
    sizes: sizes(2, 4, 5, 5, 3),
  },
  {
    id: "fern-tee",
    number: 7,
    name: "Fern Tee",
    price: 44,
    status: "in_stock",
    description: "All-over cyanotype of ferns and wild grasses, exposed in the sun in Hackney.",
    colourways: [
      colourway("07", "a", "prussian", "Prussian blue", "#1F5C98"),
      colourway("07", "b", "rust", "Rust terracotta", "#B8582E"),
    ],
    sizes: sizes(4, 6, 6, 5, 2),
  },
  {
    id: "holding-on-crew",
    number: 8,
    name: "Holding On Crew",
    price: 78,
    status: "selling_fast",
    description: "Heavyweight crew with two skeleton hands chain-stitched over the chest.",
    colourways: [
      colourway("08", "a", "black", "Black", "#171717"),
      colourway("08", "b", "grey-marl", "Grey marl", "#AAAAA8"),
    ],
    sizes: sizes(1, 0, 2, 2, 0),
  },
  {
    id: "cloud-nine-tee",
    number: 9,
    name: "Cloud Nine Tee",
    price: 46,
    status: "in_stock",
    description: "Sky blue tee with raised puff-print clouds drifting up from the hem.",
    colourways: [
      colourway("09", "a", "sky", "Sky", "#A9CDEA"),
      colourway("09", "b", "lilac", "Lilac", "#CDB5DD"),
    ],
    sizes: sizes(6, 7, 4, 6, 5),
  },
  {
    id: "one-of-one-tee",
    number: 10,
    name: "One of One Tee",
    price: 40,
    status: "drops_friday",
    description: "Stone tee printed with one giant cracked fingerprint. On the rail this Friday.",
    colourways: [
      colourway("10", "a", "stone", "Stone", "#D9D2C2"),
      colourway("10", "b", "black-lime", "Black, acid lime", "#1A1A1A"),
    ],
    sizes: sizes(8, 8, 8, 8, 8),
  },
];

export const STATUS_LABEL: Record<OffTheRailProduct["status"], string> = {
  in_stock: "In stock",
  selling_fast: "Selling fast",
  drops_friday: "Drops Friday",
};
